### ISSUE TITLE
Unable to install a new instance of this app

### ISSUE THREAD

**Issue by ashrafsaqib** [ashrafsaqib/ServiceZen-services-delivery-management-system#4]
Due to following lines , the php artisan commands is throwing error as the following code runs sql query to find service categories each time app is run 
https://github.com/ashrafsaqib/chatgpt-services-delivery-management-system/blob/27455381f8e8853970055867dc8190a3b8778753/app/Providers/AppServiceProvider.php#L33

Steps to reproduce error 
1. git clone in a new folder
2. run php artisan migrate command it will throw error for service categories table due to the above lines

**Comment by Hamza00003** [comment]
issue resolved
